# Global values
replicas: 1

# Selenium Hub configuration
hub:
  image:
    repository: selenium/hub
    tag: 4.28.1
    pullPolicy: Always
  env:
    - name: SE_GRID_TIMEOUT 
      value: "300000"
    - name: SE_SESSION_REQUEST_TIMEOUT 
      value: "300000"
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

# Chrome Node configuration
chromeNode:
  image:
    repository: selenium/node-chrome
    tag: 4.28.1
    pullPolicy: Always
  env:
    - name: SE_EVENT_BUS_HOST
      value: "selenium-hub"
    - name: SE_EVENT_BUS_PUBLISH_PORT 
      value: "4442"
    - name: SE_EVENT_BUS_SUBSCRIBE_PORT 
      value: "4443"
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  autoscaler:
    enabled: true
    minReplicas: "1"
    maxReplicas: "2"
    targetCPUUtilization: 90
    targetMemoryUtilization: 90

# Automation Tests configuration
automation:
  image:
    repository: automation/qa
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  volume:
    mountPath: /app/results
