# Global values
replicas: 1

# Selenium Hub configuration
hub:
  image:
    repository: selenium/hub
    tag: 4.28.1
    pullPolicy: Always
  env:
    SE_GRID_TIMEOUT: "300000"
    SE_SESSION_REQUEST_TIMEOUT: "300000"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

# Chrome Node configuration
chromeNode:
  image:
    repository: selenium/node-chrome
    tag: 4.28.1
    pullPolicy: Always
  env:
    SE_EVENT_BUS_HOST: "selenium-hub"
    SE_EVENT_BUS_PUBLISH_PORT: "4442"
    SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  autoscaler:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 90
    targetMemoryUtilization: 90

# Automation Tests configuration
automation:
  image:
    repository: your-repo/your-automation-image
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  volume:
    mountPath: /app/results