# Chrome Node Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "selenium-grid.fullname" . }}-chrome-node-autoscaler
  labels:
    {{- include "selenium-grid.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "selenium-grid.fullname" . }}-chrome-node
  minReplicas: {{ .values.chromeNode.autoscaler.minReplicas }}
  maxReplicas: {{ .values.chromeNode.autoscaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .values.chromeNode.autoscaler.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .values.chromeNode.autoscaler.targetMemoryUtilization }}