name: Python application for Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  REGION: eu-north-1
  TAG_TEST: qa-tests-${{ github.sha }}
  REPO: 727646471145.dkr.ecr.eu-north-1.amazonaws.com/hteymur/qa-automation

jobs:
  verify-app:
    name: Verify Application
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version required by your project

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install --no-cache-dir -r ApplicationTests/requirements.txt

      # Run pylint linting
      - name: Run pylint linting
        run: |
          pylint --fail-under=8 ApplicationTests/main.py

  # This job depends on the verify-app job
  build-publish:
    runs-on: ubuntu-latest
    name: Build and Push docker images
    needs: verify-app 

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Build docker image 
    - name: Build docker image
      run: |
        docker build -t $REPO:$TAG_TEST -f DockerFiles/DockerfileTest .
    
    # Get AWS creds
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    # Publish docker image 
    - name: Publish docker image
      run: |
        docker push $REPO:$TAG_TEST

